### PR TITLE
Proposed site structure & Material theme.

### PR DESCRIPTION
**Pull request by badarotti**
Hello everyone,

Live demo: https://badarotti.github.io/openSUSE-docs-revamped/

### Site structure
The proposed site structure satisfies what we agreed upon, it's user friendly hand holding type documentation while also catering for professional in special sections. Please read the index page for full description.

Added a temporary Doc Team On-boarding section for our use during development.

**Please comment on the structure and language so that I can finalize this and the writers can start their work on an agreed upon framework.**

### Theme
I changed the theme to [Material](https://squidfunk.github.io/mkdocs-material/) since it turns out to have a lot useful features and styling options.

I customized or enabled the following features:
- openSUSE branding. The logo needs to be enlarged
- Added the github repo info top right
- Revision date at the bottom of the page
- favicon
- Instant navigation
- Extensive admonitions
- Blocks and syntax highlighting within blocks
- Permalinks anchors on header
- TOC depth set to 5
- Editing link on each page linking to the github page. On the live demo site, most will not work as these pages havn't been pulled yet
- Emojis

More mods will be made as I go through the configuration options of mkdocs and the Material theme

Your feedback is appreciated 
Regards, 
Badr

### CODE REVIEW

**Comment by surprized** [comment]
I like this.
I thought Material was good but after digging a little bit into the theming it seems like it is bloated.
I'd like to see how to implement dark mode, but we can save that for later :)

**Comment by apinter** [comment]
I like the layout a lot, but we will also need to implement the openSUSE branding as well. I assume the theme can be changed via html and css?

**Comment by surprized** [comment]
Forgot to reply: yes, they talk about it here [https://www.mkdocs.org/user-guide/styling-your-docs/]()
What I can't see clear is how to change them dynamically, as in, selecting dark mode. I would like to also know how can we read the user's preference as set in the browser; i.e. our wiki automatically selects dark mode when the user decides to expose this via the config _privacy.resistFingerprinting_ on Firefox, I don't know about Chromium-based browsers, though.

**Comment by badarotti** [comment]
Description changed, please read again.

**Comment by Nycticorax** [comment]
It's a great commit! Thanks for that. Can you please PR to https://github.com/Nycticorax/openSUSE-docs-revamped/tree/material-theme-new-structure? I'd like to keep dev as "neutral" as possible so that we use it as a baseline to compare things against.
Also, let's try to separate concerns as much as possible, i.e. design stuff and contents stuff ought to be PR'ed separately.
We're just starting so for this one time it's OK

**Comment by badarotti** [comment]
> It's a great commit! Thanks for that. Can you please PR to https://github.com/openSUSE/openSUSE-docs-revamped/tree/material-theme-new-structure instead? I'd like to keep dev as "neutral" as possible so that we use it as a baseline to compare things against.
> Also, let's try to separate concerns as much as possible, i.e. design stuff and contents stuff ought to be PR'ed separately.
> We're just starting so for this one time it's OK

Done, I guess we can delete this PR then ...

**Pull request closed without merging**
