### PR TITLE
Adding dnf

### PR DESCRIPTION
**Pull request by apinter**

### CODE REVIEW

**Review by why-not-try-calmer — CHANGES_REQUESTED** [review]
Comments by section names.

General question: should we drop the "#" and use `sudo` instead so that the user can simply copy-paste instructions?

__DNF package manager__
- I'd suggest adding an answer to the question "I am on oS land. I bow to King Zypper. Why would I want to use dnf / libdnf?
- I'd say "RPMs-based distributions", or or perhaps even better, something like"package managers using primarily the .rpm package format", to emphasis which is which (distro / package manager). I'd also say a word about the Fedora origin.
- I'd add the fact it uses `libdnf` for backend
- I'd be more precise about automaticity and parallelism; I'd use instead the words "background" and/or "scheduled" updates instead of the first notion, and the word "concurrent" instead of the second notion -- it's not strictly speaking parallelism because it's just multithreaded. I know it's some hair-cutting but let's not import this popular mistake into the docs.

The rest I've taken care of myself -- hope it's ok

**Comment by apinter** [comment]
> * I'd be more precise about automaticity and parallelism; I'd use instead the words "background" and/or "scheduled" updates instead of the first notion, and the word "concurrent" instead of the second notion -- it's not strictly speaking parallelism because it's just multithreaded. I know it's some hair-cutting but let's not import this popular mistake into the docs.



> Comments by section names.
> 
> General question: should we drop the "#" and use `sudo` instead so that the user can simply copy-paste instructions?
> 
> **DNF package manager**
> 
> * I'd suggest adding an answer to the question "I am on oS land. I bow to King Zypper. Why would I want to use dnf / libdnf?
> * I'd say "RPMs-based distributions", or or perhaps even better, something like"package managers using primarily the .rpm package format", to emphasis which is which (distro / package manager). I'd also say a word about the Fedora origin.
> * I'd add the fact it uses `libdnf` for backend
Please check the updates.

> * I'd be more precise about automaticity and parallelism; I'd use instead the words "background" and/or "scheduled" updates instead of the first notion, and the word "concurrent" instead of the second notion -- it's not strictly speaking parallelism because it's just multithreaded. I know it's some hair-cutting but let's not import this popular mistake into the docs.
Following the upstream wording used in the `DNF` docs - and in the configuration files - I doubt that we should change this. The reason I use these "terms" is because it is used like that upstream and planning to keep it close to upstream.

> The rest I've taken care of myself -- hope it's ok
Which I possibly overwrote because I've just noticed this line. Because I'm a muppet...................

**Comment by why-not-try-calmer** [comment]
> Following the upstream wording used in the DNF docs - and in the configuration files - I doubt that we should change this. The reason I use these "terms" is because it is used like that upstream and planning to keep it close to upstream.
I understand, and that's a very good reason. But consider https://stackoverflow.com/questions/1050222/what-is-the-difference-between-concurrency-and-parallelism. It's not essential for the quality of the document, of course, but I don't see what benefit we bring to the readers by importing this mistaken / misleading use of the term "parallelism" in our docs. Don't the readers deserve not to be mislead? :)

**Comment by apinter** [comment]
> I understand, and that's a very good reason. Also it's not essential for the quality of the document, of course, but I don't see what benefit we bring to the readers by importing this [mistaken / misleading](https://stackoverflow.com/questions/1050222/what-is-the-difference-between-concurrency-and-parallelism.) use of the term "parallelism" in our docs. Don't the readers deserve not to be mislead, no matter the source of the misleading material? :)

You know what? You're right. Lets change it.

**Comment by apinter** [comment]
> I understand, and that's a very good reason. Also it's not essential for the quality of the document, of course, but I don't see what benefit we bring to the readers by importing this [mistaken / misleading](https://stackoverflow.com/questions/1050222/what-is-the-difference-between-concurrency-and-parallelism.) use of the term "parallelism" in our docs. Don't the readers deserve not to be mislead, no matter the source of the misleading material? :)

e728004 should address this and with that I believe the changes requested has been implemented.

**Pull request merged**
