### PR TITLE
Add prerequisites install proprietary.md

### PR DESCRIPTION
**Pull request by camckay**

### CODE REVIEW

**Comment by camckay** [comment]
Just some initial changes to give a better explanation of what the different drivers are and where to get more information. The naming convention seems to cause a lot of confusion.

**Comment by Nycticorax** [comment]
> Just some initial changes to give a better explanation of what the different drivers are and where to get more information. The naming convention seems to cause a lot of confusion.

Hello @camckay and thanks for this commit. Your concerns about clarity in the names of the driver is much appreciated. Speaking of clarity, may I suggest that this page be modified so as to make it clear which steps the user still needs to follow to actually take advantage of an installed Nvidia proprietary driver? I mean, can we answer the following questions directly on this page?

- If the user follows the step written here, does they still need to do something else? What is automatic, what requires more?
- What sort of GPU acceleration can the user expect? Is the entire rendering offloaded to Nvidia? Or is the rendering of only specific apps? And what if the user has both an Nvidia card and an integrated GPU (i.e. Intel)?
- What _recommendations_  can we make to cover this scenarios? (a) Wants to offload just on demand, for example for games and GPU-intensive programs, and otherwise wants the Nvidia GPU turned off to maximize battery usage. (b) Want to choose when to offload by restarting their desktop session , and wants to offload the entire rendering in that case. (c) Does not want to choose anything, wants to always offload to Nvidia. (c) Does not want to choose anything, wants to always offload to Nvidia except for the desktop environment, which should be dealt with by the integrated GPU.

It's a lot of questions of course, but can you add something to this file that would answer one or several of them?

**Comment by camckay** [comment]
Absolutely. I want to address those issues and hybrid graphics as well. There are a lot of new laptops on the market with combinations of AMD CPUs and Nvidia GPUs, and we seem to be sorely lacking in documentation for those. I am not a developer and don't frequently use git. So for my first commit I wanted to keep it small and make sure I had everything set up correctly. Thank you for your quick feedback!

**Comment by Nycticorax** [comment]
> Absolutely. I want to address those issues and hybrid graphics as well. There are a lot of new laptops on the market with combinations of AMD CPUs and Nvidia GPUs, and we seem to be sorely lacking in documentation for those. I am not a developer and don't frequently use git. So for my first commit I wanted to keep it small and make sure I had everything set up correctly. Thank you for your quick feedback!

Fine, so I'll merge for now. Looking forward to reading a PR that explores these topics a bit more. :)

**Pull request merged**
