### PR TITLE
Update microos_getting_started.md

### PR DESCRIPTION
**Pull request by benjamingwynn**
fix snaps: apparmor.service must be enabled for snapd to work, see https://github.com/ubuntu/microk8s/issues/249#issuecomment-525372725

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
> fix snaps: apparmor.service must be enabled for snapd to work, see [ubuntu/microk8s#249 (comment)](https://github.com/ubuntu/microk8s/issues/249#issuecomment-525372725)

Is it an acceptable assumption to make that it will be enabled by default in the context of the instructions specified by the document? If so, wouldn't it be better to phrase the requirement that do justice to this assumption, i.e. "here we presuppose that you have apparmor enabled (which should be the case by default). make sure that this is the case by doing < instruction for enabling apparmor >".

**Comment by apinter** [comment]
FWIW AppArmor is enabled by default on MicroOS and on every, major openSUSE distro.

**Comment by syds-git** [comment]
It will change in the near future btw, as SELinux will become default for MicroOS instead of AppArmor

**Comment by syds-git** [comment]
It will change in the near future btw, as SELinux will become default for MicroOS instead of AppArmor

**Comment by why-not-try-calmer** [comment]
> It will change in the near future btw, as SELinux will become default for MicroOS instead of AppArmor

Okay so then my initial suggestion applies I think: make it an assumption, make it explicit, and link the instruction for ensuring this to the assumption, if you don't mind, @benjamingwynn

**Comment by syds-git** [comment]
I meant with near future, it is in Staging:G right now, and when that is in factory we will need to change a lot more in the first setup thing, as in Gnome desktop version flathub will be enabled at first boot + some flatpaks are installed (i.e. firefox and gnome calculator)

**Comment by syds-git** [comment]
and probably gnome software (and discover) can even perform upgrades of the system, not need to open a terminal to do a `sudo transactional-update dup` command by yourself

**Comment by why-not-try-calmer** [comment]
Alright, I'll let you guys come together on what's best. I'll follow and come back at merge time.

**Comment by benjamingwynn** [comment]
> FWIW AppArmor is enabled by default on MicroOS and on every, major openSUSE distro.

I don't *think* this is the case, AppArmor wasn't enabled on my fresh install of MicroOS (KDE) yesterday, which is why I added the instruction. It could be that the Gnome version enables AppArmor and the KDE version has it missing. I'll set up a VM later and try `sudo systemctl status apparmor` on a fresh KDE install just to be safe.

> Is it an acceptable assumption to make that it will be enabled by default in the context of the instructions specified by the document?

There is no mention of AppArmor or SELinux in the getting started document at the moment, so somebody who is more familiar with both technologies may want to add a few words. 

I also submitted an issue (#104) regarding the current steps not keeping snaps after reboot, I included a workaround from [this blog post](https://www.ypsidanger.com/23800-running-snaps-on-opensuse-microos-desktop/) - I'd be really interested to hear a better approach to this than just hacking `/snap` into the users home directory.

**Comment by why-not-try-calmer** [comment]
> > FWIW AppArmor is enabled by default on MicroOS and on every, major openSUSE distro.
> 
> I don't _think_ this is the case, AppArmor wasn't enabled on my fresh install of MicroOS (KDE) yesterday, which is why I added the instruction. It could be that the Gnome version enables AppArmor and the KDE version has it missing. I'll set up a VM later and try `sudo systemctl status apparmor` on a fresh KDE install just to be safe.
> 
> > Is it an acceptable assumption to make that it will be enabled by default in the context of the instructions specified by the document?
> 
> There is no mention of AppArmor or SELinux in the getting started document at the moment, so somebody who is more familiar with both technologies may want to add a few words.
> 
> I also submitted an issue (#104) regarding the current steps not keeping snaps after reboot, I included a workaround from [this blog post](https://www.ypsidanger.com/23800-running-snaps-on-opensuse-microos-desktop/) - I'd be really interested to hear a better approach to this than just hacking `/snap` into the users home directory.

I'm ready to merge but I'd appreciate if you could possibly inject some logic to capture this conversation; I have in mind something like
```
check if AppArmor is enabled already with <command1>, if enabled then <command2>, else <command3>
``

**Comment by benjamingwynn** [comment]
@why-not-try-calmer I added some more detail including some useful reading links for Ubuntu tech

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I added some more detail including some useful reading links for Ubuntu tech

Great, I think it's ready for merge.

**Pull request merged**
