### PR TITLE
Added zypper.md

### PR DESCRIPTION
**Pull request by daviddyess**
- My concept for an in-depth Zypper page, currently residing under the Advance Topics section.
- I attempted to condense the content with collapsibles in a manner that allowed the navigation links to remain useful. 
  - I admit the headers could be revised to be more readable in the navigation
- I added some examples, but didn't finish them, in case this concept isn't what is desired

**This PR adds the definition list to markdown (def_list) in the mkdocs.yml file**

### CODE REVIEW

**Review by Nycticorax — CHANGES_REQUESTED** [review]
Hi David, this is a terrific first PR so thank you for that!
I like you idea of using collapseable boxes. Will draw inspiration from it.
Here are some suggestions, however:

1. Your "Usage" section is likely to grow. For this reason I would anticipate on future additions by giving the material you write inside boxes, their own subsections, with a clear and simple title. If this means replacing the boxes with plain text (i.e. Markdown default "body text", that is fine.
2. Commands > Note and Commands > Tip could be merged. Two lone boxes on top of each other is perhaps not the best.
Nothing else regarding formatting. Next step is probably to get some peer-reviewing. If you agree with the above, edit, commit, and I will merge and finally open an Issue specifically about peer-reviewing. Thanks again and have a nice day!

**Review by Nycticorax — APPROVED** [review]
You didn't do (1) but I trust your best judgement.

**Comment by daviddyess** [comment]
> You didn't do (1) but I trust your best judgement.

Can you please elaborate on what you meant in (1)? I wasn't ignoring it, I just did (2) first! haha

**Comment by Nycticorax** [comment]
> > You didn't do (1) but I trust your best judgement.
> 
> Can you please elaborate on what you meant in (1)? I wasn't ignoring it, I just did (2) first! haha

Oh, my bad. I was suggesting you go for
```
subsection
subsection
subsection
```
instead of 
```
tiptool box
tiptool box
tiptool box
```

**Comment by daviddyess** [comment]
Thanks :) That makes sense, I'll go that direction for the next PR. ..and not worries, I should have waited to push everything at once or asked my question first.

**Comment by Nycticorax** [comment]
Review and follow up at #32 .

**Pull request merged**
