### PR TITLE
- added material to "media_choice"

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
- renamed "media_choice" to "image_choice"
- updated references
- updated python /  pipenv dependencies

Signed-off-by: Nycticorax <mrnycticorax@gmail.com>

### CODE REVIEW

**Comment by apinter** [comment]
>You will need to repeatedly tap `ESC` after hearing the "reboot" sound. This will land you to a blue prompt, allowing you to select your USB flash drive as boot target.

Not a big Windows guy, but is there a better way to word this one? On a Windows box the UEFI menu is not available?

**Comment by surprized** [comment]
Two things come to my mind:
1. What reboot sound, the motherboard piezo buzzer? Some vendors have it disabled by default.
2. I believe manufacturers haven't yet agreed on how to bring the boot menu options. Maybe a list of examples can help? (example: see Tails OS install guide).

Feb 13, 2021 10:57:34 PM Attila Pinter <notifications@github.com>:

**Comment by apinter** [comment]
This does unfold a few valid options for Win/Mac/Linux: https://tails.boum.org/install/
Windows specific boot of the usb drive here: https://tails.boum.org/install/win/usb/index.en.html

Would not rely on audible notifications as that would help little the installation efforts of people with disabilities and health conditions.

**Comment by why-not-try-calmer** [comment]
The 2 last commits should have fixed this.

**Pull request merged**
