### PR TITLE
Make the sidebar work with top-level links

### PR DESCRIPTION
**Pull request by hellcp**
This should address #57

### CODE REVIEW

**Comment by Nycticorax** [comment]
Heya, thanks for your quick reply! Unfortunately I have not been able to reproduce the fix. One thing that makes it more difficult to verify is that `mkdocs serve` will serve the content of `project/site/0.3.1`, where in fact what you typically want to serve is `project/site` tout court, because it is in the latter that the site selector is seeded. 

So to serve the actual result of your work you have to do something like `python -m http.server 8000` and see there how things render there.

**Comment by Nycticorax** [comment]
Still don't see. At I think the problem might be on my end. Can you share a screenshot of what your results and describe the steps you've taken to build and serve?

**Comment by hellcp** [comment]
Try deleting the resulting folder of build and rebuild

**Comment by Nycticorax** [comment]
Nothing. Still same page as in https://user-images.githubusercontent.com/19554213/105634794-22e16400-5e60-11eb-8531-578e80924522.png.
My steps:
```
git checkout -b hellcp-dev dev
...
mkdocs build
cd site
python -m http.server 8000
```

**Comment by Nycticorax** [comment]
Perhaps @apinter is able to reproduce?

**Comment by hellcp** [comment]
I see what I did wrong...

**Comment by Nycticorax** [comment]
I am grateful for the fixes, however I am still not able to reproduce and if you don't show your steps for reproducing it makes things difficult for me. Can't know where the culprit is.  ^__^'

**Comment by hellcp** [comment]
Yeah, I'm not sure what it is, I use the same method of testing and it works just fine

**Comment by apinter** [comment]
I just tested it and got the same welcome page as in #57, but with Home and v3.0.1 in the left hand nav bar.
photo_2021-01-25_17-25-52

**Comment by Nycticorax** [comment]
Nice, sorry @hellcp I am not sure why I am not getting this. Thanks for the good work!

**Pull request merged**
