### PR TITLE
[WIP]Step-by-step installation instruction

### PR DESCRIPTION
**Pull request by apinter**
Heavily WIP and need to confirm with the engineers a few things. Considering that I'm not a copywriter and have little to no past experience I'm open for constructive criticism ;)

EDIT: the whole thing is written in vim, ignore the spelling errors.

### CODE REVIEW

**Comment by Nycticorax** [comment]
Hey mate, thanks for that, I've tried to frantically pull / sync from this branch to serve it locally, before I finally noticed it was a draft PR which is not fetched as the regular PR. Since it info boxes and spacing don't render too well on GitHub, may I suggest we turn it into a regular PR? Usually what I do is to open an Issue about everything we introduce to the docs for reviewing purposes, so there is no problem merging even if heavily WIP. Also it will help others inject their own amendments.

I've read it and it think it's going to in the right direction. However I think we might use some discipline as far as structure, in view of the fact that this doc is probably going to be used as a side-by-side reference for people installing. Following this logic how about structuring the doc by using identical names for your (sub)sections as Yast? Makes it easy to alt-tab between Yast and Firefox when people are going to read this.

Also another idea: Yast will trigger events at certain points, which may depend on the context of previous choices, network availability, etc. What do you think of trying to cover all these events with info boxes (or boxes of other types, I cannot remember which types are available)? This will make these things pop out from the text and make the doc resemble the real thing even more.

An other thing I would suggest is stating exactly the conext you're presupposing, for example which installation image you're assuming (if any one in particular), whether it's Leap or TW, how much network connectivity you're assuming, etc.

Finally, even though I like screenshots, I think we should be wary not too clutter things to much, especially under a "side-by-side" workflow. So I would suggest limiting the use of screenshots to only those cases where they reference actionable UI items which are not obvious to locate or which require some sort of manipulation not best described with words.

You've picked the one doc with arguably the highest stakes, so please forgive me if I am being a little bit cautious. ;P

**Comment by Nycticorax** [comment]
Nice!
As for the "same titles" thing, I had in mind the constraint that every item on the left hand side sidebar in Yast should have a section labelled with the exact same words as in Yast. Sorry if that was already the case.

**Comment by apinter** [comment]
> As for the "same titles" thing, I had in mind the constraint that every item on the left hand side sidebar in Yast should have a section labelled with the exact same words as in Yast. Sorry if that was already the case.

Yea that clarifies, thanks.

**Comment by Nycticorax** [comment]
Nice, let's follow up in #60

**Pull request merged**
