### PR TITLE
Adding placeholders on the footer

### PR DESCRIPTION
**Pull request by surprized**
Just added the openSUSE logo under overrides/.icons so we can add it on the footer and added a placeholder for the license (assuming GPLv3, but of course this has to be decided by everyone) - the [GNU Free Documentation License](https://www.gnu.org/licenses/fdl-1.3.html) could be a good candidate - . Also removed the Made with Material for Mkdocs from the footer, other structures can be modified via the same overrides folder. Everyone is welcome to edit this and propose changes.

### CODE REVIEW

**Comment by badarotti** [comment]
Here's what the official documentation has in it's footprint, perhaps we should do the same for consistency since we aim to integrate all docs together:

---
 Copyright © 2006– 2020 SUSE LLC and contributors. All rights reserved.

Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or (at your option) version 1.3; with the Invariant Section being this copyright notice and license. A copy of the license version 1.2 is included in the section entitled “GNU Free Documentation License”.

**Comment by badarotti** [comment]
I lean towards promoting the software I use. So I suggest the following footer:

Made by the [openSUSE Documentation Team](https://en.opensuse.org/openSUSE:Documentation_team) using [MkDocs](https://www.mkdocs.org/) and the [Material](https://squidfunk.github.io/mkdocs-material/) theme.

**Comment by surprized** [comment]
Update: it currently looks like this, following @badarotti's suggestion.
Added a link to the openSUSE github in the way.
fg

I assume the copyright notice you are talking about is for the LICENSE file, right?

**Comment by surprized** [comment]
> Of course, forgot about that :). There's a link in the header though

True! The footer link leads to the org "repo" and the header link to the docs repo. I'm not sure if the header link is gonna make it to the final version though, because it needs to fetch data from external sources, but it is nice to have while we finish.

> Doesn't the licensee file usually contain the whole license not just reference to it? 

The original docs repo has the LICENSE file linked to this one [common_gfdl1.2_i.xml](https://github.com/SUSE/doc-sle/blob/master/xml/common_gfdl1.2_i.xml). Seems like they also went with the GNU Free Documentation License. Also, notice the ADDENDUM at Appendix A of their Start-up Guide: [GNU Licenses](https://doc.opensuse.org/documentation/leap/startup/html/book-opensuse-startup/bk01apa.html)

**Comment by Nycticorax** [comment]
`mkdocs build` fails with `MkDocs encountered as error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')`

**Comment by surprized** [comment]
I honestly don't know what could be going wrong, because emoji support should be provided by the module [_markdown_](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/), which is required when installing mkdocs-material.

I can serve it and build it with no problems. Reminder: I am using python 3.6, which I don't think has anything to do with this, though.

**Comment by Nycticorax** [comment]
I fixed it while merging: https://github.com/openSUSE/openSUSE-docs-revamped/commit/fad6c6a20975ea723ff7f68f87fab50f034c55a2

I am sorry I need to close this now as it's fulfilled its purpose. I didn't have much choice because I couldn't push my fix to your original branch and it's rather cumbersone to introduce changes to files *unmodified* by a PR.

**Comment by surprized** [comment]
It's ok!
We should wait for the meeting to make sure we are all on the same page regarding the license, else things can get messy down the line.

**Comment by Nycticorax** [comment]
@surprized OK.
Please, can you checkout the merge branch now and confirm it's as you wanted?

**Comment by surprized** [comment]
Not sure what should I look for in fad6c6a20975ea723ff7f68f87fab50f034c55a2. Or I am misunderstanding something.

Essentially what I did is enable `custom_dir: overrides` in the YAML, add the custom footer and a logo.

**Comment by Nycticorax** [comment]
@surprized Y the question is simply is those produce the result you want in https://github.com/openSUSE/openSUSE-docs-revamped/pull/7. If Y I can merge further to dev.

**Comment by surprized** [comment]
No, the YAML remains unchanged and the overrides folder does not exist.

**Comment by Nycticorax** [comment]
> No, the YAML remains unchanged and the overrides folder does not exist.

Okay, in that case can you make a PR to https://github.com/openSUSE/openSUSE-docs-revamped/tree/material-theme-new-structure to fix that?

**Pull request closed without merging**
