### PR TITLE
Adding notes to hybrid-graphics

### PR DESCRIPTION
**Pull request by surprized**
Add note about bbswitch and X gpu screens
Consider taking a look at the AMDGPU offload part - in theory just launching with the env DRI_PRIME=1 should do the trick for all open source drivers (IIRC this includes nouveau, didn't bother to test)

### CODE REVIEW

**Review by why-not-try-calmer — CHANGES_REQUESTED** [review]
Thanks, is fine... except for the weird numbering you've introduced. May I ask you if you'd consider fixing it?

**Comment by surprized** [comment]
Sure, The reason why I did it was because it can be confusing to enumerate something with, e.g., 2. and see a 5. come out; weird markdown things. Numbering everything with a **1.** will make it obvious if someone ever runs into this issue. As explained [here](https://riptutorial.com/markdown/example/1805/numbered-lists) markdown actually ignores the numbers.

**Comment by why-not-try-calmer** [comment]
I understand that, but the result is not amazing either...image
I've introduced several adjustements to fix this and to make the document easier to read (NB: there are nested `ifs` that we may want to remove later. This will require more work.)

**Comment by surprized** [comment]
To be honest I don't think the enumeration is a good fit for this section. I think we could rework a little bit the content and add notes about DRI_PRIME=1 for AMD gpus, if we can get someone to test it.

**Comment by why-not-try-calmer** [comment]
> To be honest I don't think the enumeration is a good fit for this section. I think we could rework a little bit the content and add notes about DRI_PRIME=1 for AMD gpus, if we can get someone to test it.

I agree. Even my last attempt is not that good. I'll leave it like that for some days. Feel free to babysit this one and add a comment when you are ready for a merge.

**Comment by surprized** [comment]
I think it is good in the current state, please take a look :)

**Review by why-not-try-calmer — APPROVED** [review]

**Comment by why-not-try-calmer** [comment]
Nice work!

**Pull request merged**
