### PR TITLE
[WIP]: Adding time zone and user settings to Leap installer

### PR DESCRIPTION
**Pull request by apinter**

### CODE REVIEW

**Comment by Nycticorax** [comment]
Some suggestions about the content:
8<----------------------------------------------
## Before you continue
1. "Before you continue" => we could use something more specific, and use it for all documents, perhaps something like "Assumptions" or "Preconditions" or "Requirements"?

2. assumption that no other operating system alongside the under installation oS OS is too strong an assumption for me. I am sure we can do better!

## Minimum system requirements
3. do we really need to strong recommend more than 4GB? would be disappointing

4. 40 GB disk space => hum this is an interesting point. On my TW laptop `sudo btrfs fi du -s /.snapshots` reports 483.17M Exclusive (split between 6 partitions). I haven't studied this but people are unlikely to use more than 15-20 snapshots at any time and this probably does not scale linearly. That being said, I almways feel a little bit squeezed on my 50 GB partition. From which I propose:
- we need to recommend more than 40
- the reason for the recommendation is not really btrfs, but more likely the fact that people will be using the distro as main workhorse, especially if they want to have some fun with games and flatpaks.

### Precautions
5. Following the logic of remark (2), can we give the user an idea how to boot from UEFI (which most users know under the misused name "BIOS")?

8<---------------------------------------------
will continue later with the rest.

**Comment by apinter** [comment]
> ## Before you continue
> 1. "Before you continue" => we could use something more specific, and use it for all documents, perhaps something like "Assumptions" or "Preconditions" or "Requirements"?

Haven't settled on anything yet, the "Before you continue" bit is there as a place holder. Requirements or something along those lines would be indeed better.

> 2. assumption that no other operating system alongside the under installation oS OS is too strong an assumption for me. I am sure we can do better!

"This guide also assumes that you will have no other Linux, Windows or MacOS operating systems alongside openSUSE after you are done installing." meaning that you will not dual-boot. Frankly, I'm not sure why I thought that this would covered elsewhere :/ Will correct that. Probably will include a section at the EOF for dual-booting so it is not melding with the full oS install.

> ## Minimum system requirements
> 1. do we really need to strong recommend more than 4GB? would be disappointing
Yes. So these docs are mostly targeting users who will install oS as a desktop in which case 4GB is very slim. And not due to system requirements, but because of the applications. I'm running a very old laptop on 4GB and if I have FF with a few tabs, VSCode, Telegram and a terminal open together at once I can see it swapping out to hard drive. Because of the applications being used 4GB+ is strongly recommended in order to enjoy a smooth system. New laptops are also coming wiht 

> 2. 40 GB disk space => hum this is an interesting point. On my TW laptop `sudo btrfs fi du -s /.snapshots` reports 483.17M Exclusive (split between 6 partitions). I haven't studied this but people are unlikely to use more than 15-20 snapshots at any time and this probably does not scale linearly. That being said, I almways feel a little bit squeezed on my 50 GB partition. From which I propose:
> 
> * we need to recommend more than 40
> * the reason for the recommendation is not really btrfs, but more likely the fact that people will be using the distro as main workhorse, especially if they want to have some fun with games and flatpaks.

40GB is the bare minimum to be able to install openSUSE along with apps and safely use snapshots. 16GB and below, snapper will be disabled. I don't think that there is anything wrong with this, especially if we follow through with including dual-booting as well. Some people may not have access to larger storage drives than 120-250GB and if one is dual-booting that suddenly looks even smaller. 
FWIW the system requirements are from the original docs here: https://doc.opensuse.org/documentation/leap/startup/html/book-opensuse-startup/art-opensuse-installquick.html
And the minimum system requirements for Windows 10 ^_^: https://support.microsoft.com/en-us/windows/windows-10-system-requirements-6d4e9a79-66bf-7950-467c-795cf0386715

> ### Precautions
> 1. Following the logic of remark (2), can we give the user an idea how to boot from UEFI (which most users know under the misused name "BIOS")?
> 
> 8<---------------------------------------------
> will continue later with the rest.
Can include a little generic snippet in an info box I guess. However, we could include BIOS boot as well. Some people prefer BIOS over UEFI or have only BIOS in their computers.

**Comment by Nycticorax** [comment]
some thoughts for discussion:
8<-----------------------------------
### Minimum system requirements (replying to your last comment)
1. CPU specs

Even though I recognize the accuracy of this line, I think the details might be a little overwhelming for very new users. Why don't we just say something like "x86_64 (Intel or AMD), see here (link) if you have an ARM processor"?

2. Disk space

> So these docs are mostly targeting users who will install oS as a desktop in which case
> 4GB is very slim. And not due to system requirements, but because of the applications.

I think the same argument (catering for new users using Leap as desktop with many applications) we get the result that 40GB disk space is too tight, and that realistically we should recommend more. That was what I was trying to say :)

### Precautions
3. ??foreign?? (line 19)

### Network settings
> your network configuration will not be transferred from _Wicked_ to _Network Manager_.

See however: https://yast.opensuse.org/blog/2021-01-25/sprint-116

> if you choose to use _Network Manager_ (NM) instead of _Wicked_

I suggest you clarify where that choice occurs (after installing?).

### List of online repositories
> These repositories

Can we be more explicit? Like "the official repositories set by default" or something like that?

### Local user
> This is useful if you're installing openSUSE over another distribution.

"over"? not sure I get it

**Comment by apinter** [comment]
> some thoughts for discussion:
> 8<-----------------------------------
> 
> ### Minimum system requirements (replying to your last comment)
> > CPU specs
> 
> Even though I recognize the accuracy of this line, I think the details might be a little overwhelming for very new users. Why don't we just say something like "x86_64 (Intel or AMD), see here (link) if you have an ARM processor"?

Ok.

> > Disk space
> > So these docs are mostly targeting users who will install oS as a desktop in which case
> > 4GB is very slim. And not due to system requirements, but because of the applications.
> 
> I think the same argument (catering for new users using Leap as desktop with many applications) we get the result that 40GB disk space is too tight, and that realistically we should recommend more. That was what I was trying to say :)

Not sure if it's wise to recommend something higher as minimum requirements for disk space tbh :/
Also this:
```
$ sudo btrfs fi df -h /                                                                      
Data, single: total=30.01GiB, used=28.76GiB
System, single: total=4.00MiB, used=16.00KiB
Metadata, single: total=1.01GiB, used=712.31MiB
GlobalReserve, single: total=58.33MiB, used=0.00B
```

> ### Precautions
> > ??foreign?? (line 19)

Yes, "Foreign OS" is how YaST is also categorizing other operating systems AFAIK.

> ### Network settings
> > your network configuration will not be transferred from _Wicked_ to _Network Manager_.
> 
> See however: https://yast.opensuse.org/blog/2021-01-25/sprint-116

It is not yet tho.

> > if you choose to use _Network Manager_ (NM) instead of _Wicked_
> 
> I suggest you clarify where that choice occurs (after installing?).

Reasonable. Ok.

> ### List of online repositories
> > These repositories
> 
> Can we be more explicit? Like "the official repositories set by default" or something like that?

Ok.

> ### Local user
> > This is useful if you're installing openSUSE over another distribution.
> 
> "over"? not sure I get it

Will clarify.

**Comment by apinter** [comment]
> ### Precautions
> > ??foreign?? (line 19)

Just noticed that this is actually how it is present in the file and not an outraged question o.O
Will fix...

**Pull request closed without merging**
